# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # força o host do DB para o serviço "db"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data:
